version: "0.1"
services:
  frontend:
    build: 
      context: ./map_app_frontend
      target: runner
    container_name: map_app_frontend
    ports:
      - 8080:80
    depends_on:
      - search_service
      - navigation_service

  search_service_base:
    build:
      context: ./services/map_app_search_service/map_app_search_service_base
      target: map-app-search-service-dep-build
      tags:
        - map-app-search-service-rel-env
      args:
        - CONANFILE=conanfile.txt
        - ARTIFACTS_NAME=search-service-dependencies-rel
        - CONAN_BUILD_TYPE=Release

  search_service:
    build:
      context: ./services/map_app_search_service
      target: runner
    container_name: map_app_search_service
    hostname: search-service
    ports:
      - 12345:12345
    depends_on:
      - search_service_base
    secrets:
      - mapbox_token

  navigation_service:
    build:
      context: ./services/map_app_navigation_service
      target: runner
    container_name: map_app_navigation_service
    hostname: navigation-service
    ports:
      - 3000:3000
    secrets:
      - mapbox_token

secrets:
  mapbox_token:
    file: mapbox_token.txt