name: Create cluster

on:
  workflow_dispatch:
    inputs:
      target_cloud:
        type: choice
        description: "Cloud"
        options:
        - AWS
        - Azure
jobs:
  aws_run:
    runs-on: ubuntu-latest
    if: inputs.target_cloud == 'AWS'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0

      - name: Install eksctl
        run: |
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Create cluster
        run: eksctl create cluster -f k8s_cluster.yml

  azure_run:
    runs-on: ubuntu-latest
    if: inputs.target_cloud == 'Azure'

    env:
      AKS_NAME: MapAppAks
      RESOURCE_GROUP_NAME: rg_MapApp
      REGION_NAME: germanywestcentral
      ACR_NAME: MapAppRegistry
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create cluster
        uses: azure/CLI@v1.0.9
        with:
          inlineScript: az aks create -n $AKS_NAME -g $RESOURCE_GROUP_NAME -l $REGION_NAME --node-count 1

      - name: Attach container registry to cluster
        uses: azure/CLI@v1.0.9
        with:
          inline_script: az aks update -n $AKS_NAME -g $RESOURCE_GROUP_NAME --attach-acr $ACR_NAME

